### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by ghost** [laaabaseball/Yourls-Popular-Links#2]
Hello,

I have **YOURLS 1.7.9** installed on **infinityfree** webhost and put the plugin in **user/plugins** and the **popularlinks.php** in **pages folder** but it seems not working, it only shows empty page no results. ANY HELP ???

http://qtez.pw/yourls
http://qtez.pw/yourls/popularlinks

**Comment by laaabaseball** [comment]
unsupported/not enough info provided
