### ISSUE TITLE
Links that are too long alter the length of the table

### ISSUE THREAD

**Issue by ingcelsi** [laaabaseball/Yourls-Popular-Links#8]
Pleasee see this image
![image](https://user-images.githubusercontent.com/18316794/203760531-0867411c-6533-417a-92da-7c86ca10b0e6.png)

To fix this add the bolded styles in your php code of plugin.php:

.popular-links {
    border-color: #313131;
    border-collapse: collapse;
    **width: auto;**
}

.popular-links td, th {
    padding: 8px;
    border-color: #313131;
    text-align: center;
    **word-break: break-all;**
}

**Comment by laaabaseball** [comment]
fixed in commit 1cd70f1191943ff24b1e02cba0775c160677530d
